defaults:
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
      category: "blog"
authors:
  derrekc:
    display_name: Derrek Croney
    email: derrek.croney@duke.edu
    twitter: derreklemar
    github: derrekc

sass:
	sass_dir:	_sass

markdown: redcarpet

highlighter: pygments